source 'https://Jasperav@bitbucket.org/Jasperav/specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’11.0’

use_frameworks!
target 'JVGradientLayer_Tests' do
  pod 'JVGradientLayer', :path => '../'
  
  
end
